# Generated by Django 3.2.4 on 2021-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
