# Generated by Django 3.2.4 on 2021-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_inventory_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='discount',
            name='old_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
