# Generated by Django 3.2.4 on 2021-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210712_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
