# Generated by Django 3.2.4 on 2021-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=None, max_length=70, null=True, upload_to='accounts/static/img/user'),
        ),
    ]
