# Generated by Django 3.2.4 on 2021-09-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbought',
            name='updated_at',
        ),
    ]
