# Generated by Django 3.2.4 on 2021-08-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingcompany',
            name='contry',
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='country',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.county')),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='county',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='order.county'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingcompany',
            name='county',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='order.county'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='county',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='order.county'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.city'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.city'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.city'),
        ),
    ]
