# Generated by Django 3.2.4 on 2021-09-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210829_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='client_phone_number',
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='courier_phone_number',
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='shipping_company',
        ),
        migrations.AddField(
            model_name='deposit',
            name='postal_code',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='street',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='AWB',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_type',
            field=models.CharField(choices=[('F', 'Person'), ('C', 'Company')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='street',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='ShippingCompany',
        ),
    ]
