# Generated by Django 3.2.4 on 2021-09-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210909_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_reg_no', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('IBAN', models.CharField(max_length=15)),
                ('fiscal_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.order')),
            ],
        ),
    ]
